repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/mercadolibre/fury_websec-git-hooks
    rev: v1.0.5
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]
  # Datasec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/mercadolibre/fury_datasec-git-hooks
    rev: 1.0.1
    hooks:
      - id: pre_commit_hook
        stages: [commit]
        verbose: true
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args:
        - --config=.flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^notebooks
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.0
    hooks:
    - id: jupytext
      files: ^notebooks
      args: [--pre-commit-mode, --sync]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --config
          - pyproject_black.toml
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    - id: pylint
      args:
        - --rcfile=.pylintrc
        - --disable=wrong-import-order
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        exclude: ^tests
        args: [
            "--install-types",
            "--non-interactive",
            --config-file=mypy.ini
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
