test:
  secret_name: "GCP_ADV_CRED_TEST"
  project_id: "ads-dmp-audiencias"
  dataset_id: "DMP_TEST"
  wf_dq_table_name: "DMP_DQ_WORKFLOW_CONTROL"
prod:
  secret_name: "GCP_ADV_CRED_PROD"
  project_id: "ads-dmp-prod"
  dataset_id: "DMP_PROD"
  wf_dq_table_name: "DMP_DQ_WORKFLOW_CONTROL"
