test_refactor:
  global_config: ../global_config.yml
  etl:
    table_name: "DMP_GENDER_HISTORICAL_MVP"
    truncate_on_write: False
    path: etl_resources
    script: populate_query_gender
  sanity_checks:
    table_name: "DMP_DQ_LOGS" # validar que existe
    truncate_on_write: False
    path: sc_resources
    step_source:
      path: source
      steps:
    step_result:
      path: result
      steps:
        - rule
  availability:
    path: ../data_quality
    script_anomaly_detection: anomaly_detection
    script_check: availability # availability.sql
    coverage_step_source: 0.95
    coverage_step_result: 0.95

