test_refactor:
  project:
    test:
      secret_name: "GCP_ADV_CRED_TEST"
      project_id: "ads-dmp-audiencias"
      dataset_id: "DMP_TEST"
    prod:
      secret_name: "GCP_ADV_CRED_PROD"
      project_id: "ads-dmp-prod"
      dataset_id: "DMP_PROD"
  etl_process:
    table_name: "DMP_CUSTOM_AUDIENCES"
  sanity_checks:
    path: sc_resources
    step_source:
      path: source
      steps:
        - rule11
        - rule2
        - rule3
    step_result:
      path: result
      steps:
        - rule4
        - rule5
        - rule6

